##---
# Source: weave-cloud/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: weave-cloud
  namespace: weave
  labels:
    app: weave-cloud
    chart: weave-cloud-0.3.0
    release: weave-cloud
    heritage: Tiller